### ISSUE TITLE
cannot download the data

### ISSUE THREAD

**Issue by shuoyes** [Dousia/MetricPrompt#1]
when i perform the instruction that `cd download_text_classification.sh`,find it has 404 Not Found

**Comment by Dousia** [comment]
Thank you for your interest in our work.
The data download script was curated from [OpenPrompt](https://github.com/thunlp/OpenPrompt/blob/main/datasets/download_text_classification.sh) project, but now the corresponding file links seem to be invalid. I will fix the issue ASAP. If you are in a hurry, you can try to download the data files from huggingface ([agnews](https://huggingface.co/datasets/ag_news), [dbpedia](https://huggingface.co/datasets/dbpedia_14), [yahoo](https://huggingface.co/datasets/yahoo_answers_topics)), and revise the loading code in [dataloader.py](https://github.com/Dousia/MetricPrompt/blob/main/dataloader.py) for compatibility.

**Comment by Dousia** [comment]
@shuoyes Hi, sry for the late updates. I have fixed errors with data downloaders. You can run experiments with the latest code directly, and the datasets will be downloaded automatically.
